// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDajmD1rRk4N6hg1MfRvy6d78t5b6s_S7Q',
    appId: '1:477012196994:web:c239148f8c9b2b4fbb7e9b',
    messagingSenderId: '477012196994',
    projectId: 'we-source-you',
    authDomain: 'we-source-you.firebaseapp.com',
    storageBucket: 'we-source-you.firebasestorage.app',
    measurementId: 'G-9RT4KSYDLH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM7BI09qfrZfcJBwr5XJdi_FthajLhP28',
    appId: '1:477012196994:android:3182d6ceccfcb8eebb7e9b',
    messagingSenderId: '477012196994',
    projectId: 'we-source-you',
    storageBucket: 'we-source-you.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqu45SyF1Dj_QVKwiVND190eAjpUoZFoo',
    appId: '1:477012196994:ios:e0874767097cfe7ebb7e9b',
    messagingSenderId: '477012196994',
    projectId: 'we-source-you',
    storageBucket: 'we-source-you.firebasestorage.app',
    iosClientId: '477012196994-4a9h23fbp5980pj2b4p8to27p81h58je.apps.googleusercontent.com',
    iosBundleId: 'com.example.weSourceYou',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqu45SyF1Dj_QVKwiVND190eAjpUoZFoo',
    appId: '1:477012196994:ios:e0874767097cfe7ebb7e9b',
    messagingSenderId: '477012196994',
    projectId: 'we-source-you',
    storageBucket: 'we-source-you.firebasestorage.app',
    iosClientId: '477012196994-4a9h23fbp5980pj2b4p8to27p81h58je.apps.googleusercontent.com',
    iosBundleId: 'com.example.weSourceYou',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDajmD1rRk4N6hg1MfRvy6d78t5b6s_S7Q',
    appId: '1:477012196994:web:c59542b25ee0e6ffbb7e9b',
    messagingSenderId: '477012196994',
    projectId: 'we-source-you',
    authDomain: 'we-source-you.firebaseapp.com',
    storageBucket: 'we-source-you.firebasestorage.app',
    measurementId: 'G-6X7ET2WJCS',
  );

}